version: "3"
services:
  client:
    image: node:16.15.0-bullseye-slim
    volumes:
      - type: bind
        source: ./client
        target: /client
    working_dir: /client
    command: ["tail", "-f", "/dev/null"]
    environment:
      - NO_UPDATE_NOTIFIER=true
