version: "3"
services:
  alpine:
    image: alpine:3.15
    volumes:
      - type: bind
        source: .
        target: /bind
      - ./:/default
      - ./:/delegated:delegated
    command: ["tail", "-f", "/dev/null"]
